"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the background service plugin"
permissions = [
    "allow-start",
    "allow-stop",
    "allow-is-running",
    "allow-get-service-state",
    "allow-install-service",
    "allow-uninstall-service",
]
